# Generated by Django 4.1.7 on 2023-04-03 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djswig', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('cityId', models.IntegerField(primary_key=True, serialize=False)),
                ('CityName', models.CharField(max_length=50, null=True)),
                ('CityUrl', models.CharField(max_length=200, null=True)),
            ],
            options={
                'db_table': 'citydat',
            },
        ),
        migrations.DeleteModel(
            name='cities',
        ),
        migrations.DeleteModel(
            name='Restaurants',
        ),
    ]
