# Generated by Django 4.1.7 on 2023-04-03 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djswig', '0006_alter_city_options_alter_restaurantdat_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DjswigCities',
        ),
        migrations.DeleteModel(
            name='DjswigRestaurants',
        ),
    ]
