# Generated by Django 4.1.7 on 2023-04-03 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djswig', '0002_city_delete_cities_delete_restaurants'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'managed': False},
        ),
    ]
