# Generated by Django 4.1.7 on 2023-04-03 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djswig', '0004_authgroup_authgrouppermissions_authpermission_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={},
        ),
        migrations.AlterModelOptions(
            name='restaurantdat',
            options={},
        ),
    ]
